call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_dsva_los_3day.pt DSVA mimiciii codeemb
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_dsva_los_7day.pt DSVA mimiciii codeemb
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_dsva_mortality.pt DSVA mimiciii codeemb
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_dsva_readmission.pt DSVA mimiciii codeemb
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_va_los_3day.pt VA mimiciii codeemb
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_va_los_7day.pt VA mimiciii codeemb
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_va_mortality.pt VA mimiciii codeemb
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_va_readmission.pt VA mimiciii codeemb
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_vc_los_3day.pt VC mimiciii codeemb
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_vc_los_7day.pt VC mimiciii codeemb
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_vc_mortality.pt VC mimiciii codeemb
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_eicu_vc_readmission.pt VC mimiciii codeemb
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_dsva_los_3day.pt DSVA eicu codeemb
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_dsva_los_7day.pt DSVA eicu codeemb
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_dsva_mortality.pt DSVA eicu codeemb
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_dsva_readmission.pt DSVA eicu codeemb
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_va_los_3day.pt VA eicu codeemb
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_va_los_7day.pt VA eicu codeemb
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_va_mortality.pt VA eicu codeemb
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_va_readmission.pt VA eicu codeemb
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_vc_los_3day.pt VC eicu codeemb
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_vc_los_7day.pt VC eicu codeemb
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_vc_mortality.pt VC eicu codeemb
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_codeemb_mimic_vc_readmission.pt VC eicu codeemb
call transfer_predict.cmd dpe C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_dpe_los_3day.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd dpe C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_dpe_los_7day.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd dpe_mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_dpe_mortality.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd dpe_readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_dpe_readmission.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_los_3day.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_los_7day.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_mortality.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_dsva_readmission.pt DSVA mimiciii descemb_bert
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_va_los_3day.pt VA mimiciii descemb_bert
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_va_los_7day.pt VA mimiciii descemb_bert
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_va_mortality.pt VA mimiciii descemb_bert
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_va_readmission.pt VA mimiciii descemb_bert
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_vc_los_3day.pt VC mimiciii descemb_bert
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_vc_los_7day.pt VC mimiciii descemb_bert
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_vc_mortality.pt VC mimiciii descemb_bert
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_eicu_vc_readmission.pt VC mimiciii descemb_bert
call transfer_predict.cmd dpe C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_dpe_los_3day.pt DSVA eicu descemb_bert
call transfer_predict.cmd dpe C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_dpe_los_7day.pt DSVA eicu descemb_bert
call transfer_predict.cmd dpe_mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_dpe_mortality.pt DSVA eicu descemb_bert
call transfer_predict.cmd dpe_readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_dpe_readmission.pt DSVA eicu descemb_bert
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_los_3day.pt DSVA eicu descemb_bert
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_los_7day.pt DSVA eicu descemb_bert
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_mortality.pt DSVA eicu descemb_bert
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_dsva_readmission.pt DSVA eicu descemb_bert
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_va_los_3day.pt VA eicu descemb_bert
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_va_los_7day.pt VA eicu descemb_bert
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_va_mortality.pt VA eicu descemb_bert
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_va_readmission.pt VA eicu descemb_bert
call transfer_predict.cmd los_3day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_vc_los_3day.pt VC eicu descemb_bert
call transfer_predict.cmd los_7day C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_vc_los_7day.pt VC eicu descemb_bert
call transfer_predict.cmd mortality C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_vc_mortality.pt VC eicu descemb_bert
call transfer_predict.cmd readmission C:\gatech\bd4h\p1\DescEmb3\xfer\ehr_descemb_mimic_vc_readmission.pt VC eicu descemb_bert
